# Generated by Django 3.2.25 on 2024-06-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_auto_20240621_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Hipertensão', 'Hipertensão'), ('Hipotensão', 'Hipotensão'), ('Arritmia', 'Arritmia'), ('Taquicardia', 'Taquicardia')], default='', max_length=100),
        ),
    ]
