# Generated by Django 3.2.25 on 2024-06-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0005_fotografia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('HIPERTENSÃO', 'Hipertensão'), ('HIPOTENSÃO', 'Hipotensão'), ('BRADICARDIA', 'Bradicardia'), ('TAQUICARDIA', 'Taquicardia')], default='', max_length=100),
        ),
    ]
